version: '3'
services:
  jekyll: 
    image: jekyll/jekyll:4.0
    container_name: bernardopacheco-net
    environment:
        - JEKYLL_ENV=docker
    # force_polling makes the linux box watch for any changes to files, then it will regenerate
    # livereload gets the browser to automatically refresh when changes happen to files
    # command: jekyll serve --force_polling --livereload
    command: >
      sh -c "npm install &&
             npm install -g grunt-cli &&
             grunt && 
             jekyll serve --force_polling --livereload"
    ports:
        - 4000:4000
        - 35729:35729
    volumes:
        - ./:/srv/jekyll